language: node_js
sudo: true
dist: trusty

node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta


before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

install:
 - npm install -g @angular/cli
 - npm install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    # get this by install installing travis cli
    # https://docs.travis-ci.com/user/deployment/heroku/
    # run travis encrypt $(heroku auth:token)
    secure: <secure heroku api key>
  app:
    master: <name of your app>
