language: node_js
sudo: true
dist: trusty

node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta


before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

install:
 - npm install -g @angular/cli
 - npm install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: vM3WETJPoqJfojsFdoE2yU3A4SmBkiLSU5PVm4NKFsLqPqj/Uic5wv8DZlZlC0a/KbuRgV7+p5r+bevVG/BwreaUgfjizSgTw0L9lk43M062LeDGyh8CobvnKdfdZ3AhyC0AWOKQ9UOAqwXOkxY2RDE/qpZn/TpllEYvNfcCPoZj40z2hxvFdtl0+sBzRpFF4KvyBWfFRMX5C9/0va+fqi4nx2mfkcDXbenfpoABft2It0ymd4hdxWSgBY/Je73gQ5rjNi7K0CQvudA8NeZ5hghZHYVsTP6bxM2P46t5IsqiZYwj96//oUY09eHWrbZODbz7C/AIgliPrINDTWUyzjJkUIRIHyTm7a2QmXro9aAvg1yop6xoryGFQn11vYuqOLwkRpetgczsrzNrsG0QQTcHwLDr4Yj7J8vPwmeUAnGy21UPt1a74ZVvZGeTHXxiEOIWDjBBkZAtofrhgkvbViNQeZAsuHAg36XExffyUDtQVUUcZnftzzLUwiLUMFJOLjycyZpmCilNp8JT/lWechNoiuGkR7cmgsjrLjqwJdfx3qlulpNIAxo3PMXKdBjARLWi7eVy0vVRYYVoLAgaNk777Gpv2jpt+ZSM/HOrKqrUc3XLnyHNJ27smJGjG5QHR5KJISgxSNaHkljTA9TphNWLvx2LHoqEPwRfJOk25F4=
  app:
    master: ng2-app-deploy
